#!/usr/bin/env python
# encoding: utf-8

name = "Enol_Ether_Formation_charge_separated/groups"
shortDesc = ""
longDesc = """                        
*1O(+) = *2C(-) - *3C - *4R <=>  *1O - *2C = *3C - *4R
"""

template(reactants=["Root"], products=["perfluorinated_alkene"], ownReverse=False)

reverse = "Enol_Ether_Transformation"
reversible = True

reactantNum = 1

productNum = 1

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['GAIN_PAIR', '*1', 1],    
    ['LOSE_PAIR', '*2', 1],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['FORM_BOND', '*2', 1, '*4'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 C       u0 p1 c-1  {2,D} {3,S}
2 *1 O       u0 p1 c+1  {1,D} 
3 *3 C       u0  {1,S} {4,S}
4 *4 [F1s,H]       u0 {3,S}
""",
    kinetics = None,
)
