#!/usr/bin/env python
# encoding: utf-8

name = "CO_CF_bond_dissociation_charge_separated/groups"
shortDesc = ""
longDesc = """
one carbon-oxygen and one carbon-fluorine bond is broken (although not on the same carbon). Oxygen and fluorine then bond to the "opposite" carbon. This family applies the recipe to the charge separated resonance structure. 


    R                 *4R
    |                  |
R - *1C(-) = *2O(+) - *3C   <-->   R - *3C = *2O    +   *4R - *1C - R
    |                                    |
    R                                    R
"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reverse = "association_via_CO_CF_bond_formation"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['BREAK_BOND', '*1', 1, '*2'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*4', 1, '*1'],
    ['GAIN_PAIR', '*2', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 O       u0 p1 c+1 {2,S} {3,D}
2 *3 C       u0 {1,S} {4,S}
3 *1 C       u0 p1 c-1 {1,D}
4 *4 [F1s,H] u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_4F1sH->F1s",
    group = 
"""
1 *2 O   u0 p1 c+1 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S}
3 *1 C   u0 p1 c-1 {1,D}
4 *4 F1s u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_5R!H->C",
    group = 
"""
1 *2 O   u0 p1 c+1 {2,S} {3,D}
2 *3 C   u0 {1,S} {4,S} {5,S}
3 *1 C   u0 p1 c-1 {1,D}
4 *4 F1s u0 {2,S}
5    C   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_5R!H->C_Ext-5C-R_6R!H->C",
    group = 
"""
1 *2 O   u0 p1 c+1 r0 {2,S} {3,D}
2 *3 C   u0 r0 {1,S} {4,S} {5,S}
3 *1 C   u0 p1 c-1 r0 {1,D}
4 *4 F1s u0 r0 {2,S}
5    C   u0 r0 {2,S} {6,S}
6    C   u0 r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_5R!H->C_Ext-5C-R_N-6R!H->C",
    group = 
"""
1 *2 O   u0 p1 c+1 r0 {2,S} {3,D}
2 *3 C   u0 r0 {1,S} {4,S} {5,S}
3 *1 C   u0 p1 c-1 r0 {1,D}
4 *4 F1s u0 r0 {2,S}
5    C   u0 r0 {2,S} {6,S}
6    F   u0 r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_N-5R!H->C",
    group = 
"""
1 *2 O   u0 p1 c+1 r0 {2,S} {3,D}
2 *3 C   u0 r0 {1,S} {4,S} {5,S}
3 *1 C   u0 p1 c-1 r0 {1,D}
4 *4 F1s u0 r0 {2,S}
5    F   u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-4F1sH->F1s",
    group = 
"""
1 *2 O u0 p1 c+1 {2,S} {3,D}
2 *3 C u0 {1,S} {4,S}
3 *1 C u0 p1 c-1 {1,D}
4 *4 H u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-4F1sH->F1s_Ext-3C-R_Ext-2C-R_Ext-5R!H-R",
    group = 
"""
1 *2 O   u0 p1 c+1 r0 {2,S} {3,D}
2 *3 C   u0 r0 {1,S} {4,S} {5,S}
3 *1 C   u0 p1 c-1 r0 {1,D}
4 *4 H   u0 r0 {2,S}
5    C   u0 r0 {2,S} {6,[S,B,D,T,Q]}
6    R!H ux {5,[S,B,D,T,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_4F1sH->F1s
        L3: Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_5R!H->C
            L4: Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_5R!H->C_Ext-5C-R_6R!H->C
            L4: Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_5R!H->C_Ext-5C-R_N-6R!H->C
        L3: Root_4F1sH->F1s_Ext-3C-R_Ext-5R!H-R_N-5R!H->C
    L2: Root_N-4F1sH->F1s
        L3: Root_N-4F1sH->F1s_Ext-3C-R_Ext-2C-R_Ext-5R!H-R
"""
)

