#!/usr/bin/env python
# encoding: utf-8

name = "CO_CF_bond_dissociation_charge_separated/groups"
shortDesc = ""
longDesc = """
one carbon-oxygen and one carbon-fluorine bond is broken (although not on the same carbon). Oxygen and fluorine then bond to the "opposite" carbon. This family applies the recipe to the charge separated resonance structure. 


    R                 *4R
    |                  |
R - *1C(-) = *2O(+) - *3C   <-->   R - *3C = *2O    +   *4R - *1C - R
    |                                    |
    R                                    R
"""

template(reactants=["Root"], products=["CFO_", "R_F"], ownReverse=False)

reverse = "association_via_CO_CF_bond_formation"
reversible = True

reactantNum = 1

productNum = 2

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['BREAK_BOND', '*1', 1, '*2'],    
    ['BREAK_BOND', '*3', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['FORM_BOND', '*4', 1, '*1'],
    ['GAIN_PAIR', '*2', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 C       u0 p1 c-1  {2,D}
2 *2 O       u0 p1 c+1  {1,D} {3,S}
3 *3 C       u0  {2,S} {4,S}
4 *4 [F1s,H]       u0 {3,S}
""",
    kinetics = None,
)

